# Generated by Django 2.1.2 on 2018-10-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('cardholder', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('authorization', 'authorization'), ('presentment', 'presentment'), ('settlement', 'settlement')], max_length=13)),
                ('created', models.DateTimeField(verbose_name='time when transaction was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=6)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=99)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issuerapp.Accounts')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='transfer_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='issuerapp.Transfers'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transfer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='issuerapp.Transfers'),
        ),
    ]
