# Generated by Django 2.1.2 on 2018-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuerapp', '0002_auto_20181009_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='main_currency',
            field=models.CharField(default='EUR', max_length=3),
            preserve_default=False,
        ),
    ]
