# Generated by Django 2.1.2 on 2018-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuerapp', '0004_auto_20181012_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
